apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniswap-app
  labels:
    app: uniswap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uniswap
  template:
    metadata:
      labels:
        app: uniswap
    spec:
      containers:
      - name: uniswap-app
        image: prathameshdoni/uniswap:v1
        ports:
        - containerPort: 3000
