apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  rules:
  - host: "my.uniswap.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: uniswap-service
            port:
              number: 8080