apiVersion: v1
kind: Service
metadata:
  name: uniswap-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: uniswapapp
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007