apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniswapapp
  labels:
    app: uniswapapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uniswapapp
  template:
    metadata:
      labels:
        app: uniswapapp
    spec:
      containers:
      - name: uniswapapp
        image: prathameshdoni/uniswap:latest
        ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
