apiVersion: v1
kind: Service
metadata:
  name: uniswap-service
  namespace: uniswap-2024
spec:
  type: NodePort
  selector:
    app: uniswap
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 30007
